# embed_metal_shaders.cmake -- Generate metal_shader_source.h with embedded shader source
#
# Inputs (passed via -D):
#   SHADER_DIR  -- Path to UltrafastSecp256k1/metal/shaders/
#   OUTPUT_FILE -- Path to write metal_shader_source.h
#
# Reads the 5 required shader headers (field, point, bloom, extended, hash160),
# strips #include and #pragma once lines, prepends Metal stdlib header, and
# appends inline scalar_mul_batch + generator_mul_batch kernel definitions.
# Writes the result as a C++ raw string literal.

set(SHADER_FILES
    "${SHADER_DIR}/secp256k1_field.h"
    "${SHADER_DIR}/secp256k1_point.h"
    "${SHADER_DIR}/secp256k1_bloom.h"
    "${SHADER_DIR}/secp256k1_extended.h"
    "${SHADER_DIR}/secp256k1_hash160.h"
)

set(COMBINED "")

# Prepend Metal stdlib
string(APPEND COMBINED "#include <metal_stdlib>\nusing namespace metal;\n\n")

# Read and strip each shader file
foreach(FILE ${SHADER_FILES})
    file(READ "${FILE}" CONTENT)
    # Strip #include lines
    string(REGEX REPLACE "#include [^\n]*\n" "" CONTENT "${CONTENT}")
    # Strip #pragma once lines
    string(REGEX REPLACE "#pragma once[^\n]*\n" "" CONTENT "${CONTENT}")
    string(APPEND COMBINED "${CONTENT}\n")
endforeach()

# Append inline kernel definitions (matching secp256k1_kernels.metal signatures)
string(APPEND COMBINED "
// =============================================================================
// Inline kernel definitions for BIP-352 scanning
// =============================================================================

kernel void scalar_mul_batch(
    device const AffinePoint *bases    [[buffer(0)]],
    device const Scalar256 *scalars    [[buffer(1)]],
    device AffinePoint *results        [[buffer(2)]],
    constant uint &count               [[buffer(3)]],
    uint tid [[thread_position_in_grid]]
) {
    if (tid >= count) return;
    AffinePoint base = bases[tid];
    Scalar256 k = scalars[tid];
    JacobianPoint jac = scalar_mul_glv(base, k);
    results[tid] = jacobian_to_affine(jac);
}

kernel void generator_mul_batch(
    device const Scalar256 *scalars    [[buffer(0)]],
    device AffinePoint *results        [[buffer(1)]],
    constant uint &count               [[buffer(2)]],
    uint tid [[thread_position_in_grid]]
) {
    if (tid >= count) return;
    AffinePoint gen = generator_affine();
    Scalar256 k = scalars[tid];
    JacobianPoint jac = scalar_mul(gen, k);
    results[tid] = jacobian_to_affine(jac);
}
")

# Write as C++ raw string literal header
file(WRITE "${OUTPUT_FILE}" "// Auto-generated by cmake/embed_metal_shaders.cmake -- do not edit\n")
file(APPEND "${OUTPUT_FILE}" "#pragma once\n\n")
file(APPEND "${OUTPUT_FILE}" "static const char METAL_SHADER_SOURCE[] = R\"metal_src(\n")
file(APPEND "${OUTPUT_FILE}" "${COMBINED}")
file(APPEND "${OUTPUT_FILE}" ")metal_src\";\n")
